runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /new_user
  script: new_user.app
  secure: always
- url: /increment
  script: increment.app
  secure: always
- url: /
  script: main.app
  secure: always

libraries:
- name: MySQLdb
  version: "latest"

